version: '3.8'
services:
  postgres:
    image: postgres:latest
    # volumes: 
    #   - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  elasticsearch:
    image: elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # temp for http
    ports:
      - "9200:9200"
      - "9300:9300"
  app:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - type: bind # hotswappable code
        source: ./server/
        target: /usr/src/app/
      - type: volume # preserve the modules
        target: /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    restart: unless-stopped
