version: '3.8'
services:
  app:
    # build:
    #   context: ./server/
    #   dockerfile: ./Dockerfile
    #   target: dev
    # command: [ "npm", "run", "test" ]
    # # volumes:
    # #   - type: bind # hotswappable code
    # #     source: ./server/
    # #     target: /usr/src/app/
    # #   - type: volume # preserve the modules
    # #     target: /usr/src/app/node_modules
    # depends_on:
    #   - postgres
    #   - elasticsearch
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_HOST: postgres
    #   ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
    command:
      - "npm"
      - "run"
      - "test"
