version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    image: elasticsearch:8.15.2
    environment:
      - discovery.type=single-node #questionable
    ports:
      - "9200:9200"
      - "9300:9300"
